blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados, blogs_categoria

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),
    path('blogs/categoria/<int:id>', blogs_categoria, name = "list-blogs-cat")

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView',
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from blogs.views import search_blogs
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *
from noticias.feeds import *
from .sitemaps import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    path('servicios/', todos_servicios, name='todos-servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('blogs/busqueda/', search_blogs, name = 'search-blogs'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('proyectos/categoria/<str:categoria>/', filtro_proyecto, name = 'filtro-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
   
    path('robots.txt', TemplateView.as_view(template_name='robots.txt',content_type="text/plain")),
    path('noticias/feed/', NewsFeed()),

    # path('sitemap.xml', views.index, {'sitemaps': sitemaps}),
    # path('sitemap-<section>.xml', views.sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
    #     name='django.contrib.sitemaps.views.sitemap'),
    path('sitemap.xml', views.sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
         name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

proyectos/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.template.defaultfilters import slugify
from sorl.thumbnail import ImageField, get_thumbnail
from websimas.utils import get_file_path
from django.contrib.gis.db import models as geo_models

# Create your models here.
class Departamento(models.Model):
	nombre = models.CharField(max_length=350)
	codigo = models.CharField(max_length=10)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = "Departamentos"

CAT_CHOICES = (('proyectos-recientes','Proyectos Recientes'),('experiencia','Experiencia'))

class Proyecto(models.Model):
	nombre = models.CharField(max_length=350)
	nombre_corto = models.CharField(max_length=50)
	foto = ImageField(upload_to=get_file_path)
	resumen = RichTextUploadingField()
	#departamento = models.ManyToManyField(Departamento)
	beneficiarios = models.IntegerField(blank=True, null=True)
	slug = models.SlugField(max_length=350,editable=False)
	fileDir = 'proyectos/'
	thumb = models.CharField(max_length=500,editable=False)
	ubicacion_proyecto = geo_models.MultiPointField(null=True,blank=True)
	categoria = models.CharField(choices=CAT_CHOICES, max_length=20)

	def __str__(self):
		return self.nombre

	def save(self, *args, **kwargs):
		self.slug = slugify(self.nombre)
		self.thumb = get_thumbnail(self.foto, '104x104', crop='center', quality=99)
		return super(Proyecto, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = "Proyectos"

	@property
	def get_thumb(self):
		im = get_thumbnail(self.foto, '104x104', crop='center', quality=99)
		return im.url

class FotosProyecto(models.Model):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    archivo = ImageField(upload_to=get_file_path)
    credito = models.CharField(max_length=200, blank=True, null=True)
    fileDir = 'proyectos/img/'

    class Meta:
        verbose_name_plural = "Fotos"

proyectos/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def list_proyectos(request,template='proyectos/list_proyectos.html'):
	object_list = Proyecto.objects.filter(categoria = 'proyectos-recientes').order_by('-id')
	categorias = CAT_CHOICES
	return render(request, template, locals())

def detalle_proyecto(request,template='proyectos/proyecto_detalle.html',slug=None):
	object = Proyecto.objects.get(slug = slug)
	return render(request, template, locals())

def filtro_proyecto(request,template='proyectos/list_proyectos.html',categoria=None):
	object_list = Proyecto.objects.filter(categoria = categoria).order_by('-id')
	categorias = CAT_CHOICES
	return render(request, template, locals())

templates/sitio_v2/proyectos/proyecto_detalle.html
{% extends "base.html" %}
{% load thumbnail %}
{% load leaflet_tags %}
{% block extra_css %}
    <link rel="stylesheet" href="/static/css/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    {% leaflet_js %}
    {% leaflet_css %}
{% endblock extra_css %}

{% block content %}

<style>
    #mapid { height: 100px; }
</style>

<div class="breadcrumb-area shadow dark bg-fixed text-center color-white" >
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 text-left">
                <h2 >Proyectos</h2>
            </div>
            <div class="col-md-6 col-sm-6 text-right">
                <ul class="breadcrumb">
                    <li><a href="/">Inicio</a></li>
                    <li class="active">Proyectos</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<section class="area-proyecto pdt-100 pdb-70 bg-gris">
    <div class="container">

        <div class="card-body  bg-white box-shadow">
        <div class="row">
            <div class="col-md-5">
                {% thumbnail object.foto "800x480" crop="center" as im %}
                    <img src="{{ im.url }}" alt="">
                {% empty %}
                    <img src="https://place-hold.it/800x480" alt="...">
                {% endthumbnail %}
            </div>
            <div class="col-md-7">
                <div class="info-proyecto">
                    <h4>{{object.nombre}}</h4>
                    <h5>
                        {{object.nombre_corto}}
                    </h5>
                    <div class="row">
                        <div class="col-lg-6">
                            {% if object.beneficiarios %}
                            <div class="fun-fact d-flex">
                                <div class="fun-fact-img">
                                    <img src="/static/img/iconos/icon-1.png" alt="FundRack" class="img-fluid">
                                </div>
                                <div class="fun-content text-left">
                                    <h2>{{object.beneficiarios}}</h2>
                                    <p class="m-0">Beneficiarios</p>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
				<div class="card-body bg-white">
					<div class="info-texto">                      
                       {{object.resumen|safe}}
					</div>
				</div>
            </div>
        </div>
        
        
        <div class="row text-center">
			<div class="col">
				<div class="seccion-heading-style-one mrb-30">
					<h2 class="text-color-base">Ubicación e Imágenes del Proyecto</h2>
				</div>
			</div>
		</div>
        <!-- galeria proyecto -->
        <div class="row">
            {% if object.ubicacion_proyecto %}  
            <div class="col-lg-6 mrb-20">
                {% leaflet_map "mapid" %}
            </div>
            {% endif %}
            {% if object.fotosproyecto_set.all %}
            <div class="col-lg-6 mrb-20">
                <div class="owl-proyecto owl-carousel owl-theme">
                    {% for obj in object.fotosproyecto_set.all %}
                    
                        <a href="/media/{{obj.archivo}}" data-fancybox data-caption="{{obj.nombre}} {% if obj.credito %}• Credito: {{obj.credito}}{% endif %}">
                            {% thumbnail obj.archivo "x280" crop="center" as im %}
                                <img src="{{ im.url }}" alt="">
                            {% endthumbnail %}
                        </a>
                    
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
        </div>
    </div>
</section>

{% endblock content %}
{% block extra_js %}
<script src="/static/js/owl-carousel/owl.carousel.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script>
    $('.owl-proyecto').owlCarousel({
        margin:10,
        loop:true,
        autoWidth:true,
        responsiveClass:true,
        nav: false,
        dots: true,
        lazyLoad:true,
		navText: ['<i class="fa fa-chevron"></i>', '<i class="fa fa-chevron"></i>'],
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:1,
                nav:false
            },
            1000:{
                items:1,
                nav:true,
                loop:false
            }
        }
    });
    //$(".owl-nav").addClass("sr-only");
</script>
<script>
    var map = L.map('mapid').setView([{{object.ubicacion_proyecto.0.1}}, {{object.ubicacion_proyecto.0.0}}], 7);
    mapLink = '<a href="http://openstreetmap.org">OpenStreetMap</a>';
    L.tileLayer(
        'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; ' + mapLink + ' Contributors',
        maxZoom: 18,
        }).addTo(map);

        {% for point in object.ubicacion_proyecto %}
            var marker{{forloop.parentloop.counter}}_{{forloop.counter}} = L.marker([{{point.1}}, {{point.0}}]).addTo(map);
        {% endfor %}
    

</script>

{% endblock extra_js %}