blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados, blogs_categoria

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),
    path('blogs/categoria/<int:id>', blogs_categoria, name = "list-blogs-cat")

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView',
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

noticias/urls.py
from django.urls import path
from .views import *

app_name = 'noticias'

urlpatterns =   [
    path('', HomePageView, name = "home"),
    path('subscribe/', subscribe, name = "subscribe"),
    # path('portafolio/servicios/', ListServiceView.as_view(), name = "servicios"),
    # path('portafolio/sistemas/', ListPortfolioView.as_view(), name = "portafolio1"),
    path('historia-simas/', HistoriaPageView.as_view(), name = "historia"),
    # path('quienes-somos/', QuienesPageView.as_view(), name = "somos"),
    path('noticias/', ListNewsView.as_view(), name = "noticias"),
   	path('noticias/<int:id>/<str:uri>/', DetailNewsView, name = "detalle-noticia"),
    path('contactenos/', ContactenosPageView.as_view(), name = "contactenos"),
    path('noticias/categoria/<str:slug>', notas_categoria, name = "list-noticia-cat")
]

publicaciones/urls.py
from django.urls import path, include
from .views import *

app_name = 'publicaciones'

urlpatterns = [
    path('publicaciones/', ListBooksView, name ='publicaciones'),
    path('publicaciones/filtro/<id>', FiltroListBooksView, name ='filtro-publicaciones'),
    path('publicaciones/<int:id>/<str:uri>/', DetailBooksView, name ='detalle-publicacion'),
    path('publicaciones/simas/', ListBookSimasView.as_view(), name='simas'),
    path('publicaciones/cidoc/', ListBookCidocView.as_view(), name='cidoc'),
    path('publicaciones/categoria/<str:slug>', publicaciones_categoria, name = "list-publicaciones-cat")
]



""" urlpatterns = patterns(
    'publicaciones.views',
    url(r'^publicaciones/$', ListBooksView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/(?P<id>[0-9]+)/(?P<uri>[-\w]+)/$',
        'DetailBooksView', name='detalle-publicacion'),
    url(r'^publicaciones/simas/$', ListBookSimasView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/cidoc/$', ListBookCidocView.as_view(),
        name='publicaciones'),
)
 """

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from blogs.views import search_blogs
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *
from noticias.feeds import *
from .sitemaps import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    path('servicios/', todos_servicios, name='todos-servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('blogs/busqueda/', search_blogs, name = 'search-blogs'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('proyectos/categoria/<str:categoria>/', filtro_proyecto, name = 'filtro-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
   
    path('robots.txt', TemplateView.as_view(template_name='robots.txt',content_type="text/plain")),
    path('noticias/feed/', NewsFeed()),

    # path('sitemap.xml', views.index, {'sitemaps': sitemaps}),
    # path('sitemap-<section>.xml', views.sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
    #     name='django.contrib.sitemaps.views.sitemap'),
    path('sitemap.xml', views.sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
         name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

templates/search/search_blogs.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load embed_video_tags %}
{% load el_pagination_tags %}

{% block content %}
<!-- Header Breadcrumbs-->
<header class="breadcrumbs-type-1">
    <div class="container breadcrumbs--breadcrumbs-inner">
        <h1 class="breadcrumbs-inner--page-title">
            Cambiando Vidas
        </h1>
        <ul class="breadcrumbs-inner--breadcrumbs-list">
            <li>
                <a href="/">
                    Inicio
                </a>
            </li>
            <li>
                <a href="#">
                    Cambiando Vidas
                </a>
            </li>
        </ul>
    </div>
</header>
<!-- Blog Metro -->
<section class="blog-metro">
    <div class="container">
      <div class="row">
        <div class="buttons-sort col-xl-9">
            <a href="{% url 'noticias:noticias' %}" class="buttons-sort--button active-button" data-filter="*">Todos</a>
            {% for obj in categorias %}
                <a href="{% url 'noticias:list-noticia-cat' obj.0 %}" class="buttons-sort--button">{{obj.1}}</a>
            {% endfor %}
        </div>
        <div class="col-xl-3 sticky-sidebar">
            <div class="sidebar-wrapper right-sidebar">
                <aside class="sidebar-wrapper--sidebar">
                    <div class="sidebar--sidebar-widget">
                        <div class="sidebar-widget--search">
                            <form class="search-form" action="/publicaciones/busqueda/" method="GET">
                              {{search.q}}
                              <button type="submit"><i class="fa fa-search double-flash"></i></button>
                            </form>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
      </div>
    </div>
    <div class="four-column-container">
        <div class="grid" data-grid-layout-mode="packery" data-grid-transition="0.6" data-grid-stagger="80">
            {% for result in page.object_list %}
            <div class="grid--grid-item {% if forloop.first or forloop.counter == 2 %}grid--grid-item-50{% else %}grid--grid-item-25{% endif %}">
                <div class="blog-hover-effect-wrapper">
                    <div class="grid-item--grid-inner">
                        {% thumbnail result.object.foto "1920x1280" crop="center" as im %}
                        <img src="{{ im.url }}" alt="" class="img-fluid">
                        {% empty %}
                        <img src="http://via.placeholder.com/1920x1280" class="img-fluid" alt="">
                        {% endthumbnail %}
                        <div class="grid-inner--post-content">
                            <div class="post-content--tag">
                                <span>{{result.object.idcatblog}}</span>
                            </div>
                            <div class="post-content--meta">
                                <div class="meta--date">
                                    <p>{{result.object.fecha|date:"M d, Y"}}</p>
                                </div>
                                <div class="meta-separator"><p>|</p></div>
                                <a href="{% url 'blogs:detalle-blog' result.object.id result.object.uri %}" class="meta--author"><p>{{result.object.idautor}}</p></a>
                            </div>
                            <div class="post-content--title">
                                <a href="{% url 'blogs:detalle-blog' result.object.id result.object.uri %}"><h5>{{result.object.blog}}</h5></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="pagination">
					{% if page.has_previous or page.has_next %}

					 {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}" class="endless_page_link">{% endif %}{% if page.has_previous %}< </a>{% endif %}
					 <span class="endless_page_current">{{ page.number }} de {{ page.paginator.num_pages }}</span>

					 {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}" class="endless_page_link">{% endif %} {% if page.has_next %}> </a>{% endif %}

					 {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
	$("#id_q").val("{{request.GET.q}}");
</script>
{% endblock extra_js %}

templates/search/search_notas.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load embed_video_tags %}
{% load el_pagination_tags %}

{% block content %}
<!-- Header Breadcrumbs-->
<header class="breadcrumbs-type-1">
    <div class="container breadcrumbs--breadcrumbs-inner">
        <h1 class="breadcrumbs-inner--page-title">
            Actualidad
        </h1>
        <ul class="breadcrumbs-inner--breadcrumbs-list">
            <li>
                <a href="/">
                    Inicio
                </a>
            </li>
            <li>
                <a href="#">
                    Actualidad
                </a>
            </li>
        </ul>
    </div>
</header>
<!-- Blog Metro -->
<section class="blog-metro">
    <div class="container">
      <div class="row">
        <div class="buttons-sort col-xl-9">
            <a href="{% url 'noticias:noticias' %}" class="buttons-sort--button active-button" data-filter="*">Todos</a>
            {% for obj in categorias %}
                <a href="{% url 'noticias:list-noticia-cat' obj.0 %}" class="buttons-sort--button">{{obj.1}}</a>
            {% endfor %}
        </div>
        <div class="col-xl-3 sticky-sidebar">
            <div class="sidebar-wrapper right-sidebar">
                <aside class="sidebar-wrapper--sidebar">
                    <div class="sidebar--sidebar-widget">
                        <div class="sidebar-widget--search">
                            <form class="search-form" action="/notas/busqueda/" method="GET">
                              {{search.q}}
                              <button type="submit"><i class="fa fa-search double-flash"></i></button>
                            </form>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
      </div>
    </div>
    <div class="four-column-container">
        <div class="grid" data-grid-layout-mode="packery" data-grid-transition="0.6" data-grid-stagger="80">
            {% for result in page.object_list %}
            <div class="grid--grid-item {% if forloop.first or forloop.last %}grid--grid-item-50{% elif forloop.counter == 15 %}grid--grid-item-50{% elif not forloop.counter|divisibleby:8 %}grid--grid-item-25{% else %}grid--grid-item-50{% endif %}">
                <div class="blog-hover-effect-wrapper">
                    <div class="grid-item--grid-inner">
                        {% if result.object.foto %}
                            {% thumbnail result.object.foto "1920x1280" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% endthumbnail %}
                        {%elif result.object.url %}
                            {% video result.object.url as my_video %}
                            {% thumbnail my_video.thumbnail "1920x1280" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% endthumbnail %}
                            {% endvideo %}
                        {% else %}
                            <img src="http://via.placeholder.com/1920x1280" class="img-fluid" alt="">
                        {% endif %}
                        <div class="grid-inner--post-content">
                            <div class="post-content--tag">
                                <span>{{result.object.categoria.first}}</span>
                            </div>
                            <div class="post-content--meta">
                                <div class="meta--date">
                                    <p>{{result.object.fecha|date:"M d, Y"}}</p>
                                </div>
                                <div class="meta-separator"><p>|</p></div>
                                <a href="{% url 'noticias:detalle-noticia' result.object.id result.object.uri %}" class="meta--author"><p>{{result.object.idautor}}</p></a>
                            </div>
                            <div class="post-content--title">
                                <a href="{% url 'noticias:detalle-noticia' result.object.id result.object.uri %}"><h5>{{result.object.noticia}}</h5></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="pagination">
					{% if page.has_previous or page.has_next %}

					 {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}" class="endless_page_link">{% endif %}{% if page.has_previous %}< </a>{% endif %}
					 <span class="endless_page_current">{{ page.number }} de {{ page.paginator.num_pages }}</span>

					 {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}" class="endless_page_link">{% endif %} {% if page.has_next %}> </a>{% endif %}

					 {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
  $("#id_q").attr("placeholder", "Buscar...");
	$("#id_q").val("{{request.GET.q}}");
</script>
{% endblock extra_js %}

templates/search/search_publicacion.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<style>
    .content--title-subtitle h3 {
        font-size: 18px !important;
    }
</style>
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                Publicaciones
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="#">
                        Publicaciones
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- Portfolio -->
    <section class="portfolio-metro small-section">
        <div class="container">
          <div class="row">
            <div class="buttons-sort col-md-6">
                <a href="{% url 'publicaciones:publicaciones' %}" class="buttons-sort--button active-button" data-filter="*">Todos</a>
                {% for obj in tematicas %}
                    <a href="{% url 'publicaciones:filtro-publicaciones' obj.0 %}" class="buttons-sort--button">{{obj.1}}</a>
                {% endfor %}
            </div>
            <div class="buttons-sort col-md-3">
                <div class="button-wrapper" style="margin-right:10px">
                    <a class="button btn-type-1" href="{% url 'publicaciones:cidoc' %}">CIDOC</a>
                </div>
                <div class="button-wrapper">
                    <a class="button btn-type-1" href="{% url 'publicaciones:simas' %}">SIMAS</a>
                </div>
            </div>
            <div class="col-xl-3 sticky-sidebar">
                <div class="sidebar-wrapper right-sidebar">
                    <aside class="sidebar-wrapper--sidebar">
                        <div class="sidebar--sidebar-widget">
                            <div class="sidebar-widget--search">
                                <form class="search-form" action="/publicaciones/busqueda/" method="GET">
                                  {{search.q}}
                                  <button type="submit"><i class="fa fa-search double-flash"></i></button>
                                </form>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
          </div>

        </div>
        <div class="three-column-container">
            <div class="grid" data-grid-layout-mode="masonry" data-grid-transition="0.6" data-grid-stagger="80">
                {% for result in page.object_list %}
                <div class="grid--grid-item grid--grid-item-25">
                    <div class="scale-3d--wrapper">
                        {% comment %} <div class="grid-item--grid-inner scale-3d-hover-effect tilt-wrapper"
                                data-tilt-value="5" data-tilt-speed="1200"
                                data-tilt-scale="1" data-tilt-perspective="600">
                            {% thumbnail result.object.portada "360x500" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% empty %}
                            <img src="http://via.placeholder.com/360x500" alt="" class="img-fluid">
                            {% endthumbnail %}
                            <a class="grid-inner--description-wrapper" href="{% url 'publicaciones:detalle-publicacion' result.object.id result.object.uri %}">
                                <div class="description-wrapper--content">
                                    <div class="content--tag">
                                        <p>{{result.object.idcategoria.first}}</p>
                                    </div>
                                    <div class="content--title-subtitle">
                                        <h3>{{result.object.publicacion|truncatewords:6}}</h3>
                                    </div>
                                    <div class="content--date">
                                        <p>{{result.object.fecha|date:"d F Y"}}</p>
                                    </div>
                                </div>
                            </a>
                        </div> {% endcomment %}
                        <div class="grid-hover">
                          <figure class="effect-layla">
                            {% thumbnail result.object.portada "500x600" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% empty %}
                            <img src="http://via.placeholder.com/500x600" alt="" class="img-fluid">
                            {% endthumbnail %}
                            <figcaption>
                              <div class="scale-3d--wrapper">
                                <div class="description-wrapper--content">
                                    <div class="content--tag">
                                        <p>{{result.object.idcategoria.first}}</p>
                                    </div>
                                    <br>
                                    <div class="content--title-subtitle">
                                        <p>{{result.object.publicacion|truncatewords:6}}</p>
                                    </div>
                                    <br>
                                    <div class="content--date">
                                        <p>{{result.object.fecha|date:"d F Y"}}</p>
                                    </div>
                                </div>

                              </div>
                                <a href="{% url 'publicaciones:detalle-publicacion' result.object.id result.object.uri %}">View more</a>
                            </figcaption>
                          </figure>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
						<div class="pagination">
							{% if page.has_previous or page.has_next %}

							 {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}" class="endless_page_link">{% endif %}{% if page.has_previous %}< </a>{% endif %}
							 <span class="endless_page_current">{{ page.number }} de {{ page.paginator.num_pages }}</span>

							 {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}" class="endless_page_link">{% endif %} {% if page.has_next %}> </a>{% endif %}

							 {% endif %}
		        </div>
        </div>
    </section>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
  $("#id_q").attr("placeholder", "Buscar...");
	$("#id_q").val("{{request.GET.q}}");
</script>
{% endblock extra_js %}