blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados, blogs_categoria

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),
    path('blogs/categoria/<int:id>', blogs_categoria, name = "list-blogs-cat")

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView',
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from blogs.views import search_blogs
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *
from noticias.feeds import *
from .sitemaps import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    path('servicios/', todos_servicios, name='todos-servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('blogs/busqueda/', search_blogs, name = 'search-blogs'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('proyectos/categoria/<str:categoria>/', filtro_proyecto, name = 'filtro-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
   
    path('robots.txt', TemplateView.as_view(template_name='robots.txt',content_type="text/plain")),
    path('noticias/feed/', NewsFeed()),

    # path('sitemap.xml', views.index, {'sitemaps': sitemaps}),
    # path('sitemap-<section>.xml', views.sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
    #     name='django.contrib.sitemaps.views.sitemap'),
    path('sitemap.xml', views.sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
         name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

portafolio/models.py
# -*- coding: utf-8 -*-
from django.db import models
from fotos.models import *
from django.contrib.contenttypes.fields import GenericRelation
from otras.models import *
from django.template.defaultfilters import slugify

# Create your models here.
class Organizaciones(models.Model):
    nombre = models.CharField(max_length=250)
    iniciales = models.CharField(max_length=150)

    def __str__(self):
        return self.iniciales

TIPO_CHOICES = ((1,'Pagina web'),(2,'Aplicación movil'),(3,'Sistema web'))

class Portafolio(models.Model):
    idservicio = models.ForeignKey(Servicio,on_delete = models.CASCADE)
    servicio = models.CharField('Nombre del servicio', max_length=250)
    resumen = models.TextField()
    fecha = models.DateField('Fecha de realización')
    link = models.URLField(blank=True)
    organizacion = models.ManyToManyField(Organizaciones)
    tipo =  models.IntegerField(choices=TIPO_CHOICES,blank=True,null=True)
    slug = models.SlugField(max_length=250,editable=False)
    fotos = GenericRelation(Fotos)

    def __str__(self):
        return self.servicio
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.servicio)
        super(Portafolio, self).save(*args, **kwargs)


portafolio/views.py
from django.shortcuts import render

# Create your views here.

templates/portafolio/detalle_portafolio.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                {{object}}
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="">
                        Portafolio
                    </a>
                </li>
                <li>
                    <a href="#">
                        {{object}}
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- Single Project 1 -->
    <section class="single-project small-section">
        <div class="container">
            <div class="single-project--overview">
                <div class="overview--title">
                    <h2>Detalle del proyecto</h2>
                </div>
            </div>
            <div class="single-project--item-description">
                <div class="container">
                    <div class="row item-description--project-information">
                        <div class="col-md-3 project-information--info-wrapper"
                             data-aos="fade-up"
                             data-aos-anchor-placement="top-bottom"
                             data-aos-easing="ease-in-out"
                             data-aos-duration="800">
                            <p class="info-wrapper--subtitle">Cliente: </p>
                            <h6 class="info-wrapper--info-title"><a href="">{% for obj in object.organizacion.all %}{{obj}}{% if not forloop.last %},{% endif %}{% endfor %}</a></h6>
                        </div>
                        <div class="col-md-3 project-information--info-wrapper"
                             data-aos="fade-up"
                             data-aos-delay="100"
                             data-aos-anchor-placement="top-bottom"
                             data-aos-easing="ease-in-out"
                             data-aos-duration="800">
                            <p class="info-wrapper--subtitle">Fecha: </p>
                            <h6 class="info-wrapper--info-title">{{object.fecha|date:"M d, Y"}}</h6>
                        </div>
                        <div class="col-md-3 project-information--info-wrapper"
                             data-aos="fade-up"
                             data-aos-delay="200"
                             data-aos-anchor-placement="top-bottom"
                             data-aos-easing="ease-in-out"
                             data-aos-duration="800">
                            <p class="info-wrapper--subtitle">URL: </p>
                            <h6 class="info-wrapper--info-title"><a href="{{object.link}}">{{object.link}}</a></h6>
                        </div>
                        <div class="col-md-3 project-information--info-wrapper"
                             data-aos="fade-up"
                             data-aos-delay="300"
                             data-aos-anchor-placement="top-bottom"
                             data-aos-easing="ease-in-out"
                             data-aos-duration="800">
                            <p class="info-wrapper--subtitle">Tipo: </p>
                            <h6 class="info-wrapper--info-title"><a href="">{{object.get_tipo_display}}</a></h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="inner-wrapper--content">
                        <p>{{object.resumen}}</p>
                    </div>
                </div>
            </div>
            <br>
            <!-- Background Slider-->
            <div class="background-slider">
                <div class="background-slider-type-1">
                    <div class="swiper-container swiper-background">
                        <div class="swiper-wrapper">
                            {% for obj in object.fotos.all|dictsort:'id'|slice:'1:' %}
                            <div class="swiper-slide" style="{% thumbnail obj.imagen "1920" crop="center" as im %}background-image: url({{ im.url }}){% endthumbnail %}"></div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
  $("blockquote").wrapAll('<div class="blockquote-wrapper"></div>');
  $(".blockquote-wrapper").wrapAll('<div class="blockquote-type-2"></div>');
  $("blockquote p").each(function() {
    $("<h5>" + $(this).html() + "</h5>").replaceAll(this);
});
</script>
{% endblock extra_js %}

templates/portafolio/list_portafolio.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                Portafolio
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="#">
                        Portafolio
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- Portfolio -->
    <section class="portfolio-metro small-section">
        <div class="container">
            <div class="buttons-sort">
                <a href="{% url 'list-portafolio' %}" class="buttons-sort--button active-button" data-filter="*">Todos</a>
                {% for obj in tipos %}
                    <a href="{% url 'filtro-portafolio' obj %}" class="buttons-sort--button">{% if obj == 1 %}Pagina web{% elif obj == 2 %}Aplicación movil{% elif obj == 3 %}Sistema web{% endif %}</a>
                {% endfor %}
            </div>
        </div>
        <div class="three-column-container">
            <div class="grid" data-grid-layout-mode="masonry" data-grid-transition="0.6" data-grid-stagger="80">
                {% paginate 15 object_list %}
                {% for obj in object_list %}
                <div class="grid--grid-item grid--grid-item-33 web creative">
                    <div class="scale-3d--wrapper">
                        <div class="grid-item--grid-inner scale-3d-hover-effect tilt-wrapper"
                                data-tilt-value="5" data-tilt-speed="1200"
                                data-tilt-scale="1" data-tilt-perspective="600">
                            {% thumbnail obj.fotos.first.imagen "1920x1280" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% empty %}
                            <img src="http://via.placeholder.com/1920x1280" alt="" class="img-fluid">
                            {% endthumbnail %}
                            <a class="grid-inner--description-wrapper" href="{% url 'detalle-portafolio' obj.slug %}">
                                <div class="description-wrapper--content">
                                    <div class="content--tag">
                                        <p>{{obj.get_tipo_display}}</p>
                                    </div>
                                    <div class="content--title-subtitle">
                                        <h3>{{obj.servicio}}</h3>
                                    </div>
                                    <div class="content--date">
                                        <p>{{obj.fecha|date:"d F Y"}}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="pagination">
              {% show_pages %}
            </div>
        </div>
    </section>
</div>
{% endblock content %}